### ISSUE TITLE
Incorrect start and stop times when creating a case for RT

### ISSUE THREAD

**Issue by keninn** [Uninett/argus_ticket_rt#21]
https://ARGUSHOST/incidents/34795/

The start time visible in Request Tracker is 1 hour behind the correct time as seen in Argus.
The end time was not set in Argus at the time of creation (still an Open alarm), but the end-time (Tidspunkt - Slutt) in RT was still set to an earlier timestamp in the same day.

After using this integration a lot more I've noticed the timestamps, even when the end-time is set, are still 1 hour behind when seen in RT. Note that we are currently in CET, but on the 26.03.2023 it will be CEST.
![Skjermbilde RT](https://user-images.githubusercontent.com/128026978/225548324-d2e0853e-730b-4d9d-872f-7ae6dd3ba6e0.jpg)
![Skjermbilde Argus](https://user-images.githubusercontent.com/128026978/225548331-88367327-07ad-4007-a29b-54929ac09c11.jpg)

**Comment by hmpf** [comment]
I don't understand what is going on with End Time/Tidspunkt - Slutt:. Argus cannot update an already existing ticket when it receives an End Time after all. If End Time was copied to Tidspunkt - Slutt and there was timezone shenaningans, Tidspunkt - Slutt should have been "08.49.48".

**Comment by johannaengland** [comment]
Yes and also looking at the body of the ticket it is clear that `end_time` was infinity, otherwise the end time would've also been noted in the ticket body.

**Comment by hmpf** [comment]
The problem with "Start time"/"Tidspunkt - Start" is probably because RT stores custom field date times as UTC internally, then does not cast to local time in the web site. This is not how you do things. A worse possibility is that RT converts incoming date times to UTC, then strips the time zone information. We cannot test or fix for that.

**Comment by johannaengland** [comment]
Closing this issue since the start-time issue is fixed and the end-time error could not be replicated. Please open another issue if the end-time error shows up again.
